### ISSUE TITLE
SDMMC from SPI error - KeyError('mosi')

### ISSUE THREAD

**Issue by phodina** [timkostka/saleae_sdmmc_from_spi#5]
Hi,

I'm trying to run the protocol analyzer but I get this weird error in Logic2 (version 2.3.58).
```
  File "/home/pethod/.config/Logic/Marketplace/24/sdmmc_from_spi.py", line 374, in decode
    data.data["mosi"], data.start_time, data.end_time
```

Could you help?

**Comment by timkostka** [comment]
Does your board have separate DAT0 and CMD signals? Can you provide your capture file?

**Comment by phodina** [comment]
The issue was I used the extension provided on the Marketplace.

When I checked out this repo 0cf9422a65b0cd940048fee651dcfa438fcb92bb and followed the instructions it worked correctly without any issue.

The difference was I had to create an empty extension as there was no possibility to load one. After that I moved the files from this repo there and renamed it to recognize it in the protocol analyzers.

Not sure if there was some change in the data structure in Logic2 between the versions.

Thanks for this extension as it helps debugging MMC which does not respond to commands.

**Comment by timkostka** [comment]
Well that's weird, and unfortunate.

I can't replicate it sadly. I uninstalled my extensions, added the marketplace one, and was able to use it just fine.

Shrug.

There have been some minor changes to the data structure since this was released, but they don't affect functionality too much. Mostly just the "mytype()" showing in results.

Thanks for reporting what worked for you.

**Comment by phodina** [comment]
Thanks. I unfortunately don't have access anymore to Salae so I switched to Keysight osciloscope and simply dump the data and load it into Pulseview. I applied patches that add eMMC decoding and it solved the issues we had with the memory.

https://github.com/sigrokproject/libsigrokdecode/pull/93
