### ISSUE TITLE
 SDMMC from SPI error - KeyError('mosi') (follow up of #5)

### ISSUE THREAD

**Issue by ithinuel** [timkostka/saleae_sdmmc_from_spi#6]
Hey there,

I’m getting this same error:

```
  File "C:\Users\…\AppData\Roaming\Logic\Marketplace\24\sdmmc_from_spi.py", line 374, in decode
    data.data["mosi"], data.start_time, data.end_time
```

The extension is installed from the market place.
The source input analyzer is SPI. SPI properly processes signals.

See the attatched capture file: 
[sdcard-comm-digital-only.zip](https://github.com/user-attachments/files/16173407/sdcard-comm-digital-only.zip)

Let me know if you’d like me to try a few things.

**Comment by keck9939** [comment]
You are probably getting this error because you have Enable set to CS in the SPI analyzer (See note 4 under Create SPI Analyzer). If you set Enable to None, it will probably work. However, depending on the exact details of your SPI, the SPI analyzer may now give incorrect results even though the SDMMC now works. So you can have one or the other, but possibly not both. This is distinctly annoying.

EDIT:
I have been using the version from the marketplace, for which the above comment applies. In an attempt to fix the problem, I just got the version directly from this repository and it works fine, at least for the SPI I'm currently using. So, I suggest you try downloading from this repository and seeing if it also works for you.
Seems like there should be a way to make sure the marketplace version stays up to date.

**Comment by ithinuel** [comment]
Oh, I hadn’t seen these quirky requirements (they don’t appear in the UI when adding the analyzer).

For this analyzer to work properly the bus needs not to be shared and it’s not parsing replies, so it’s less useful than I hoped.

I tried the version from GH but I still get some errors:
```
File "C:\Users\…\AppData\Roaming\Logic\Marketplace\24\sdmmc_from_spi.py", line 375, in decode
    info = self.state.add_byte(

  File "C:\Users\…\AppData\Roaming\Logic\Marketplace\24\sdmmc_from_spi.py", line 319, in add_byte
    info = interpret_command(bits)

  File "C:\Users\…\AppData\Roaming\Logic\Marketplace\24\sdmmc_from_spi.py", line 141, in interpret_command
    assert len(bits) == 48
```

Closing because I’m probably be exporting to CSV and use Pulseview instead.
